### PR TITLE
fix nongraph joins. common query builder. Support for waterline unit tests + more operators and functions.

### PR DESCRIPTION
**Pull request by gbevan**
Now passes 119 out of 180 waterline-adapter-tests (v0.11.2).

I'm raising this PR initially for comment (not expecting you to simply merge this - as I think you would need to test against your own use cases).

I'd like to add gulp driven mocha unit-testing so we can develop our own unit-tests (on top of the waterline-adapter-tests - as arangodb has features beyond basic waterline functionality, e.g. graphs).

Please let me know your thoughts...

### CODE REVIEW

**Comment by gabriel-letarte** [comment]
Hey @gbevan, I have not maintained this project for a little while now.

What's your saying makes a lot of sense. I don't mind merging a WIP as long as stuff get resolved before the next release and that the todo stuff is clear.

Also, before I go ahead and merge, I think we should get rid of commented out code.

**Comment by gbevan** [comment]
sure.  We can use this PR as a discussion going fwd, for now.
I'll cleanup the comments too.
I'll start putting gulp and mocha test framework in place - perhaps you could have a think about what tests you would like to see around the graph support - as i've really not used that part yet (though I do plan to...)

**Comment by gbevan** [comment]
Here's a summary of the waterline adapter compliance test:
```
      ✓ should create a new record
      ✓ should return a generated PK
      ✓ should return generated timestamps
      ✓ should return a model instance
      ✓ should normalize undefined values to null
      ✓ should return rows in the correct order when creating multiple rows (131ms)
        ✓ should have saved the proper values (with auto-increment values)
      ✓ should create a set of users
      ✓ should insert 2 records verififed by find
      ✓ should return model instances
        ✓ should destroy a record
        ✓ should return an empty array when searched for
        ✓ should destroy a record
        ✓ should return an empty array when searched for
        ✓ should destroy all the records
        ✓ should return an empty array when searched for
        ✓ should not destroy any records
      ✓ should return 10 records
      ✓ should return 1 record when searching for a specific record (integer test) with find
      ✓ should return a model instance
      ✓ should work with no criteria passed in
      ✓ should return a single record
      ✓ should return a model instance
      ✓ should return null if a record is not found
      ✓ should work with just an id passed in
      ✓ should create a new record
      ✓ should return a single record
      ✓ should only have a single record in the database
      ✓ should return a model instance
      ✓ should take search criteria as values
      ✓ should accept array of objects
      ✓ should return error if search criteria length does not match values
      ✓ should create new user(s) for the one that doesn't exist
      ✓ should find a user that does exist
      ✓ should only have a single record for keys that exist
      ✓ should fail when only one arg is specified
      ✓ should return model instances
        ✓ should store proper array value
        ✓ should store proper boolean value
        ✓ should store proper date value
        ✓ should store proper float value
        ✓ should store proper integer
        ✓ should store proper object value
        ✓ should store proper string value
        ✓ should update model attributes
        ✓ should return model instances
        ✓ should work with just an ID passed in
        ✓ should work with an empty object
        ✓ should work with null values
        ✓ should update model attributes without supplying required fields
        ✓ should allow the record to be found
        ✓ endsWith should actually enforce endswith
        ✓ should escape stars
      ✓ should accurately count records
      ✓ should work with dynamic finders
      ✓ should return all the users with the given name
      ✓ should return the user with the given name
      ✓ should average by key and only return that key with the average value
      ✓ should average by multiple keys and return averages per key
          ✓ should return the user with the correct name
          ✓ should return the user with the correct name
          ✓ should have [attribute]contains() method
          ✓ should return the user with the correct name
          ✓ should return the user with the correct name
          ✓ should have [attribute]EndsWith() method
          ✓ should return records with greaterThan key
          ✓ should return records with symbolic usage > usage
          ✓ should return records with greaterThan key when searching dates
          ✓ should return records with symbolic usage > usage when searching dates
          ✓ should return records with greaterThan key when searching strings
          ✓ should return records with symbolic usage > usage when searching strings
          ✓ should return records with greaterThanOrEqual key
          ✓ should return records with symbolic usage >= usage
          ✓ should return records with greaterThanOrEqual key when searching dates
          ✓ should return records with symbolic usage >= usage when searching dates
          ✓ should return records with greaterThanOrEqual key when searching strings
          ✓ should return records with symbolic usage >= usage when searching strings
      ✓ should error if not given any calculations to do
        ✓ should return correct user
        ✓ should return a model instance
          ✓ should return an empty array
        ✓ should return an empty array
          ✓ should return records with lessThan key
          ✓ should return records with symbolic usage < usage
          ✓ should return records with lessThan key when searching dates
          ✓ should return records with symbolic usage < usage when searching dates
          ✓ should return records with lessThanOrEqual key
          ✓ should return records with symbolic usage <= usage
          ✓ should return records with lessThanOrEqual key when searching dates
          ✓ should return records with symbolic usage <= usage when searching dates
        ✓ should return the user with the given name
        ✓ should support wrapping both sides with a % sign
      ✓ should return the correct amount of records
      ✓ dynamic finder usage should return the correct amount of records
      ✓ as an option should return correct amount of records
      ✓ should get the maximum of the key
      ✓ should max multiple keys
      ✓ should max and average
      ✓ should get the minimum of the key
      ✓ should min multiple keys
      ✓ should min and average
        ✓ should return records with string usage
        ✓ should return records with symbolic usage ! usage
        ✓ should return records using not comparisons on strings
        ✓ should return a model instance
      ✓ should return a record with a single field first_name
      ✓ should return multiples records with a single field first_name
      ✓ should return a record with a single field first_name (findOne)
      ✓ should return a record with multiple fields
      ✓ in absence of SELECT modifier should return a record with all fields
      ✓ should sort records using binary notation for asc
      ✓ should sort records using binary notation desc
      ✓ should sort records using string notation for asc
      ✓ should sort records using string notation for desc
      ✓ should sort when sort is an option
      ✓ should sort records using multiple sort criteria, with first name desc
      ✓ should sort records using multiple sort criteria, with first name asc
          ✓ should return the user with the correct name
          ✓ should return the user with the correct name
          ✓ should have [attribute]StartsWith() method
      ✓ should sum by key and only return that key with the sum value
      ✓ should sum by multiple keys and return sums of all keys
      ✓ should sum and average in the same query
  1) Semantic Interface .find() should parse multi-level criteria:
  2) Queryable Interface case sensitivity .findOne() should work in a case insensitve fashion by default:
  3) Queryable Interface case sensitivity .findOne() should work with findOneBy*():
  4) Queryable Interface case sensitivity .find() should work in a case insensitve fashion by default:
  5) Queryable Interface case sensitivity .find() should work with findBy*():
  6) Queryable Interface case sensitivity special classified queries contains should work in a case insensitive fashion by default:
  7) Queryable Interface case sensitivity special classified queries startsWith should work in a case insensitive fashion by default:
  8) Queryable Interface case sensitivity special classified queries endsWith should work in a case insensitive fashion by default:
  9) Queryable Interface case sensitivity special classified queries like should work in a case insensitive fashion by default:
  10) Queryable Interface case sensitivity special characters contains should work with stars in the name:
  11) Queryable Interface Modifiers greaterThanOrEqual (>=) dates should return records with symbolic usage >= usage when searching dates as strings:
  12) Queryable Interface GroupBy Query Modifier should group by keys and sum values:
  13) Queryable Interface GroupBy Query Modifier should group by multiple keys and sum values:
  14) Queryable Interface GroupBy Query Modifier should group by keys and both sum and average values:
  15) Queryable Interface GroupBy Query Modifier should allow match query with groupBy:
  16) Queryable Interface NOT IN Query Modifier with a record should return correct user:
  17) Queryable Interface NOT IN Query Modifier without a record should return an empty array:
  18) Queryable Interface OR Query Modifier with a record should return the correct users:
  19) Queryable Interface OR Query Modifier with a record should return a model instances:
  20) Queryable Interface OR Query Modifier with a record should work with multi-level criteria options inside the OR criteria:
  21) Queryable Interface OR Query Modifier with a record should work correctly when OR is used with AND:
  22) Queryable Interface OR Query Modifier with a record should work correctly when OR is used with multiple contains modifiers:
  23) Queryable Interface OR Query Modifier without a record should return an empty array:
  24) Queryable Interface SKIP Query Modifier should return the correct amount of records:
  25) Queryable Interface SKIP Query Modifier dynamic finder usage should return the correct amount of records:
  26) Queryable Interface SKIP Query Modifier as an option should return correct amount of records:
```

What are your thoughts on the issue of case insensitive finds?  Waterline expects them to be case insensitive.  Doesn't seem right to me - also there have been reported concerns with index performance on other adapters due to this default.  I've left it as case sensitive, but with the option of using the caseSensitive: false option (see unit tests).

**Comment by gabriel-letarte** [comment]
> What are your thoughts on the issue of case insensitive finds?

If there is performance issues with case insensitive tests then I think having it default to false is a good idea.

**Comment by gbevan** [comment]
waterline adapter test (v0.11) compliance issues now down to 15:
```
      ✓ should create a new record
      ✓ should return a generated PK
      ✓ should return generated timestamps
      ✓ should return a model instance
      ✓ should normalize undefined values to null
      ✓ should return rows in the correct order when creating multiple rows (134ms)
        ✓ should have saved the proper values (with auto-increment values)
      ✓ should create a set of users
      ✓ should insert 2 records verififed by find
      ✓ should return model instances
        ✓ should destroy a record
        ✓ should return an empty array when searched for
        ✓ should destroy a record
        ✓ should return an empty array when searched for
        ✓ should destroy all the records
        ✓ should return an empty array when searched for
        ✓ should not destroy any records
      ✓ should return 10 records
      ✓ should return 1 record when searching for a specific record (integer test) with find
      ✓ should parse multi-level criteria
      ✓ should return a model instance
      ✓ should work with no criteria passed in
      ✓ should return a single record
      ✓ should return a model instance
      ✓ should return null if a record is not found
      ✓ should work with just an id passed in
      ✓ should create a new record
      ✓ should return a single record
      ✓ should only have a single record in the database
      ✓ should return a model instance
      ✓ should take search criteria as values
      ✓ should accept array of objects
      ✓ should return error if search criteria length does not match values
      ✓ should create new user(s) for the one that doesn't exist
      ✓ should find a user that does exist
      ✓ should only have a single record for keys that exist
      ✓ should fail when only one arg is specified
      ✓ should return model instances
        ✓ should store proper array value
        ✓ should store proper boolean value
        ✓ should store proper date value
        ✓ should store proper float value
        ✓ should store proper integer
        ✓ should store proper object value
        ✓ should store proper string value
        ✓ should update model attributes
        ✓ should return model instances
        ✓ should work with just an ID passed in
        ✓ should work with an empty object
        ✓ should work with null values
        ✓ should update model attributes without supplying required fields
        ✓ should allow the record to be found
        ✓ should work in a case insensitve fashion by default
        ✓ should work with findOneBy*()
        ✓ should work in a case insensitve fashion by default
        ✓ should work with findBy*()
        ✓ contains should work in a case insensitive fashion by default
        ✓ startsWith should work in a case insensitive fashion by default
        ✓ endsWith should work in a case insensitive fashion by default
        ✓ like should work in a case insensitive fashion by default
        ✓ endsWith should actually enforce endswith
        ✓ should escape stars
        ✓ contains should work with stars in the name
      ✓ should accurately count records
      ✓ should work with dynamic finders
      ✓ should return all the users with the given name
      ✓ should return the user with the given name
      ✓ should average by key and only return that key with the average value
      ✓ should average by multiple keys and return averages per key
          ✓ should return the user with the correct name
          ✓ should return the user with the correct name
          ✓ should have [attribute]contains() method
          ✓ should return the user with the correct name
          ✓ should return the user with the correct name
          ✓ should have [attribute]EndsWith() method
          ✓ should return records with greaterThan key
          ✓ should return records with symbolic usage > usage
          ✓ should return records with greaterThan key when searching dates
          ✓ should return records with symbolic usage > usage when searching dates
          ✓ should return records with greaterThan key when searching strings
          ✓ should return records with symbolic usage > usage when searching strings
          ✓ should return records with greaterThanOrEqual key
          ✓ should return records with symbolic usage >= usage
          ✓ should return records with greaterThanOrEqual key when searching dates
          ✓ should return records with symbolic usage >= usage when searching dates
          ✓ should return records with greaterThanOrEqual key when searching strings
          ✓ should return records with symbolic usage >= usage when searching strings
      ✓ should error if not given any calculations to do
          ✓ should return an empty array
        ✓ should return an empty array
          ✓ should return records with lessThan key
          ✓ should return records with symbolic usage < usage
          ✓ should return records with lessThan key when searching dates
          ✓ should return records with symbolic usage < usage when searching dates
          ✓ should return records with lessThanOrEqual key
          ✓ should return records with symbolic usage <= usage
          ✓ should return records with lessThanOrEqual key when searching dates
          ✓ should return records with symbolic usage <= usage when searching dates
        ✓ should return the user with the given name
        ✓ should support wrapping both sides with a % sign
      ✓ should return the correct amount of records
      ✓ dynamic finder usage should return the correct amount of records
      ✓ as an option should return correct amount of records
      ✓ should get the maximum of the key
      ✓ should max multiple keys
      ✓ should max and average
      ✓ should get the minimum of the key
      ✓ should min multiple keys
      ✓ should min and average
        ✓ should return records with string usage
        ✓ should return records with symbolic usage ! usage
        ✓ should return records using not comparisons on strings
        ✓ should return a model instance
      ✓ should return a record with a single field first_name
      ✓ should return multiples records with a single field first_name
      ✓ should return a record with a single field first_name (findOne)
      ✓ should return a record with multiple fields
      ✓ in absence of SELECT modifier should return a record with all fields
      ✓ should return the correct amount of records
      ✓ dynamic finder usage should return the correct amount of records
      ✓ as an option should return correct amount of records
      ✓ should sort records using binary notation for asc
      ✓ should sort records using binary notation desc
      ✓ should sort records using string notation for asc
      ✓ should sort records using string notation for desc
      ✓ should sort when sort is an option
      ✓ should sort records using multiple sort criteria, with first name desc
      ✓ should sort records using multiple sort criteria, with first name asc
          ✓ should return the user with the correct name
          ✓ should return the user with the correct name
          ✓ should have [attribute]StartsWith() method
      ✓ should sum by key and only return that key with the sum value
      ✓ should sum by multiple keys and return sums of all keys
      ✓ should sum and average in the same query
  1) Queryable Interface Modifiers greaterThanOrEqual (>=) dates should return records with symbolic usage >= usage when searching dates as strings:
  2) Queryable Interface GroupBy Query Modifier should group by keys and sum values:
  3) Queryable Interface GroupBy Query Modifier should group by multiple keys and sum values:
  4) Queryable Interface GroupBy Query Modifier should group by keys and both sum and average values:
  5) Queryable Interface GroupBy Query Modifier should allow match query with groupBy:
  6) Queryable Interface IN Query Modifier with a record should return correct user:
  7) Queryable Interface IN Query Modifier with a record should return a model instance:
  8) Queryable Interface NOT IN Query Modifier with a record should return correct user:
  9) Queryable Interface NOT IN Query Modifier without a record should return an empty array:
  10) Queryable Interface OR Query Modifier with a record should return the correct users:
  11) Queryable Interface OR Query Modifier with a record should return a model instances:
  12) Queryable Interface OR Query Modifier with a record should work with multi-level criteria options inside the OR criteria:
  13) Queryable Interface OR Query Modifier with a record should work correctly when OR is used with AND:
  14) Queryable Interface OR Query Modifier with a record should work correctly when OR is used with multiple contains modifiers:
  15) Queryable Interface OR Query Modifier without a record should return an empty array:
```
with some additional unit tests focusing on specific bugs:
```
    connection
      ✓ should establish a connection
    methods
      ✓ should create a new document in pets
      ✓ should find previously created pet by id
      ✓ should create a new document in users
      ✓ should find previously created user by id
      ✓ should find user by name
      ✓ should find user by name (case insensitive)
      ✓ should find user by name (case sensitive)
      ✓ should find user by name (case insensitive by default)
      ✓ should fail to find user by name (case sensitive)
      ✓ should update the user name by id
      ✓ should update the user name by name search
      ✓ should update the user name by name search (case insensitive)
      ✓ should support complex objects on update
      ✓ should select a top-level field using select
      ✓ should find by nested where clause
      ✓ should find by nested where clause with contains filter
      ✓ should find by nested where clause with contains filter (case insensitive)
      ✓ should find using 2 fields (AND)
      ✓ should find using 2 fields (AND) w/complex second field
      ✓ should find using 2 contains fields (AND)
      ✓ should find using 2 contains fields (AND) w/complex second field
      ✓ should populate pet
      ✓ should populate pet and find by pet name
      ✓ should not return documents with undefined field with <=
      ✓ should not return documents with undefined field with <
    drop collection(s)
      ✓ should drop the users_1 collection (50ms)
      ✓ should drop the pets_1 collection (82ms)
```

**Comment by gbevan** [comment]
only 11 left:
```
  1) Queryable Interface Modifiers greaterThanOrEqual (>=) dates should return records with symbolic usage >= usage when searching dates as strings:
  2) Queryable Interface GroupBy Query Modifier should group by keys and sum values:
  3) Queryable Interface GroupBy Query Modifier should group by multiple keys and sum values:
  4) Queryable Interface GroupBy Query Modifier should group by keys and both sum and average values:
  5) Queryable Interface GroupBy Query Modifier should allow match query with groupBy:
  6) Queryable Interface OR Query Modifier with a record should return the correct users:
  7) Queryable Interface OR Query Modifier with a record should return a model instances:
  8) Queryable Interface OR Query Modifier with a record should work with multi-level criteria options inside the OR criteria:
  9) Queryable Interface OR Query Modifier with a record should work correctly when OR is used with AND:
  10) Queryable Interface OR Query Modifier with a record should work correctly when OR is used with multiple contains modifiers:
  11) Queryable Interface OR Query Modifier without a record should return an empty array:
```

**Comment by gabriel-letarte** [comment]
Looking good!

**Comment by gbevan** [comment]
Re: 1) Queryable Interface Modifiers greaterThanOrEqual (>=) dates should return records with symbolic usage >= usage when searching dates as strings

this fails due to the waterline adapter test assuming a date format as returned by toString(), whereas arangodb returns date strings in ISO format (as per toISOString().  I've added a new unit test to our suite for the ISO string format.  I think we can ignore the above waterline test failure.  Here is the output of the new test:

```
      greaterThanOrEqual (>=)
        dates
          ✓ should return records with greaterThanOrEqual key when searching dates
          ✓ should return records with symbolic usage >= usage when searching dates
          ✓ should return records with symbolic usage >= usage when searching dates as ISO strings
```

**Comment by gbevan** [comment]
groupBy support added.  waterline test failures reduced to 7:
```
  1) Queryable Interface Modifiers greaterThanOrEqual (>=) dates should return records with symbolic usage >= usage when searching dates as strings:
  2) Queryable Interface OR Query Modifier with a record should return the correct users:
  3) Queryable Interface OR Query Modifier with a record should return a model instances:
  4) Queryable Interface OR Query Modifier with a record should work with multi-level criteria options inside the OR criteria:
  5) Queryable Interface OR Query Modifier with a record should work correctly when OR is used with AND:
  6) Queryable Interface OR Query Modifier with a record should work correctly when OR is used with multiple contains modifiers:
  7) Queryable Interface OR Query Modifier without a record should return an empty array:
```

**Comment by gbevan** [comment]
waterline adapter tests now only complains about the date string format issue i mentioned previously:
```
1) Queryable Interface Modifiers greaterThanOrEqual (>=) dates should return records with symbolic usage >= usage when searching dates as strings
```
I added my own test for ISO formatted dates returned from Arangodb.

All thats left to do is to add some unit tests around graphs support...

**Comment by gabriel-letarte** [comment]
Any update? I will gladly merge it when you think it's ready!

**Comment by gbevan** [comment]
Hi @gabriel-letarte, I need to spend a little time putting some graph related tests together.  Hopefully i'll get it done this weekend.

**Comment by gbevan** [comment]
@gabriel-letarte question: Should the models map field id to columnName '_key' or '_id'?  

Reason I ask is if I create a graph where the model states via 'id' for the edge, and id is mapped to columnName '_key' - it doesnt work: "ArangoError: invalid edge attribute".  However, if I map the id field to '_id' to all works fine.

Seems we have to have fields mapping to '_id' for createEdge() to work.

**Comment by gabriel-letarte** [comment]
@gbevan Your call, mapping the id to field `_id` seems like a reasonable decision.

**Comment by gbevan** [comment]
The current join() via a named graph is not working

I'm looking at reworking the way named graphs are defined and used.  Currently we allow for a single named (predefined outside of thislibrary) graph in the config.  I would prefer to allow named graphs to be part of the schema - like this:

```
const Waterline = require('waterline');

const UsersProfilesGraph = Waterline.Collection.extend({
  identity: 'users_profiles_graph',
  schema: 'graph',
  connection: 'arangodb',

  attributes: {
    edgeDefinitions: [
      {
        collection: 'users_profiles',
        from: ['users_1'],
        to: ['profiles_1'] 
      }
    ]
  }

});

module.exports = UsersProfilesGraph;
```
and allow as many named graphs as needed.  I think this will make a lot more sense.
Also, not sure join should use edges/graphs at all - and instead provide access to graph functions - like we do for neighbours.

I'd like to also have a think about how we can extend access to graph functionality from waterline.

Any thoughts you may have would be welcome.

**Comment by gbevan** [comment]
Summary of additional tests on top of the std waterline (v0.11) tests:
```
$ gulp test
[19:39:17] Using gulpfile ~/Documents/Brackets/sails-arangodb/gulpfile.js
[19:39:17] Starting 'mocha'...


  adapter
    connection
      ✓ should establish a connection
    methods
      ✓ should create a new document in pets (38ms)
      ✓ should find previously created pet by id (40ms)
      ✓ should create a new document in users (38ms)
      ✓ should find previously created user by id
      ✓ should find user by name
      ✓ should find user by name (case insensitive)
      ✓ should find user by name (case sensitive)
      ✓ should find user by name (case insensitive by default)
      ✓ should fail to find user by name (case sensitive)
      ✓ should update the user name by id
      ✓ should update the user name by name search
      ✓ should update the user name by name search (case insensitive)
      ✓ should support complex objects on update
      ✓ should select a top-level field using select
      ✓ should find by nested where clause
      ✓ should find by nested where clause with contains filter
      ✓ should find by nested where clause with contains filter (case insensitive)
      ✓ should find using 2 fields (AND)
      ✓ should find using 2 fields (AND) w/complex second field
      ✓ should find using 2 contains fields (AND)
      ✓ should find using 2 contains fields (AND) w/complex second field
      ✓ join should populate pet
      ✓ join should populate pet and find by pet name
      ✓ should not return documents with undefined field with <=
      ✓ should not return documents with undefined field with <
      delete
        ✓ should delete entry by name
        ✓ should delete entry in array
        ✓ should delete entry not in (with v0.11 !) array
        ✓ should delete entry not in (with v0.12 nin) array
      greaterThanOrEqual (>=)
        dates
          ✓ should return records with greaterThanOrEqual key when searching dates
          ✓ should return records with symbolic usage >= usage when searching dates
          ✓ should return records with symbolic usage >= usage when searching dates as ISO strings
      update
        ✓ should merge on update by default
        ✓ should replace on update
    Graphs
      createEdge as anonymous graph
        ✓ should create an edge
      neighbors
        ✓ should return the neighbor (profile) of the user (anonymous graph)
      join (populate) with edge collection profileOf
        ✓ should populate (join) profile and for the user (via graph)
      deleteEdge
        ✓ should delete an edge
      createEdge on named graph
        ✓ should create an edge on the named graph
      neighbors
        ✓ should return the neighbor (profile) of the user (edge coll from named graph)
      neighbors
        ✓ should return the neighbor (profile) of the user (named graph)
    drop collection(s)
      ✓ should drop the users_1 collection (69ms)
      ✓ should drop the pets_1 collection
      ✓ should drop the profiles_1 collection (50ms)
      ✓ should drop the profiles_1_id__users_1_profile (?) junctionTable collection (50ms)


  46 passing (2s)

mocha ended...
```
Please review the tests/models/*.js schemas.  The tests/adapter.test.js has examples of both anonymous and named graphs.  I think there is need for much more work here. But, these can be future pull requests...

**Comment by gabriel-letarte** [comment]
@gbevan It's really been a while since I played with Sails + ArangoDB.

I think you're currently the expert for this repo.

**Comment by gbevan** [comment]
I've updated the version in package.json to 0.3.0.  This is ready to merge and publish.

fyi - https://trello.com/b/61HDOkHt/sails-arangodb

**Comment by gabriel-letarte** [comment]
Do you want me to merge, squash & merge or do you want to reorganize history before I merge?

**Comment by gbevan** [comment]
Squash&merge is fine

**Comment by gbevan** [comment]
hi, @gabriel-letarte are you planning to publish this to npm?  It's still reporting 0.2.3 there.

**Comment by gbevan** [comment]
@gabriel-letarte I dont have the ability to publish this project under your npm account.  I could bring a fork under the umbrella of my [partoutx](https://github.com/partoutx) project - where I am using this package - and publish from there.  Let me know what approach we should follow.

**Comment by gabriel-letarte** [comment]
@gbevan Give me your email, I will add you to the list of collaborators :)

Also, if you want to take ownership of this repository, I would gladly give it to you!

**Comment by gbevan** [comment]
@gabriel-letarte I have actually already started releasing under a fork of this as https://www.npmjs.com/package/@partoutx/sails-arangodb.  I have attributed back to your original project in the readme.

**Comment by gabriel-letarte** [comment]
👍

**Pull request merged**
